# Generated by Django 2.1 on 2019-01-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('middle_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('DOB', models.DateTimeField()),
                ('profile_pic', models.ImageField(upload_to='profile_pic')),
                ('about', models.TextField()),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender')),
                ('phone_number', models.CharField(max_length=10, unique=True, verbose_name='Phone number')),
                ('website', models.URLField(blank=True, max_length=50, null=True, verbose_name='Website')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Personal Data',
            },
        ),
    ]
